AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Rikolti metadata_fetcher and metadata_mapper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MetadataFetcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: fetch_metadata
      CodeUri: metadata_fetcher/
      Handler: lambda_function.fetch_collection
      Runtime: python3.9
      Architectures:
        - x86_64
  MetadataMapperShepherdFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: shepherd_mappers
      CodeUri: metadata_mapper/
      Handler: lambda_shepherd.map_collection
      Runtime: python3.9
      Architectures:
        - x86_64
  MetadataMapperMapPageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: map_metadata
      CodeUri: metadata_mapper/
      Handler: lambda_function.map_page
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #MetadataMapperApi:
  #  Description: "API Gateway endpoint URL for Prod stage for Metadata Mapper function"
  #  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MetadataMapperFunction:
    Description: "Metadata Mapper Lambda Function ARN"
    Value: !GetAtt MetadataMapperFunction.Arn
  MetadataMapperFunctionIamRole:
    Description: "Implicit IAM Role created for Metadata Mapper function"
    Value: !GetAtt MetadataMapperFunctionRole.Arn
