Parameters:
  Env:
    Description: Environment
    Type: String
Resources:
  OpenSearchDomain:
    Properties:
      AccessPolicies:
        Statement:
          - Action: es:*
            Effect: Allow
            Principal:
              AWS: '*'
            Resource: !Sub '${OpenSearchDomain.Arn}/*'
        Version: '2012-10-17'
      AdvancedOptions:
        indices.fielddata.cache.size: 20
        indices.query.bool.max_clause_count: '1024'
        rest.action.multi.allow_explicit_index: 'true'
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: ''
          MasterUserPassword: ''
      ClusterConfig:
        InstanceCount: 3
        InstanceType: t3.medium.search
      DomainName: !Sub 'rikolti-${Env}-opensearch'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp3
      EncryptionAtRestOptions:
        Enabled: true
      EngineVersion: OpenSearch_2.3
    Type: AWS::OpenSearchService::Domain
