services:
  content_harvester:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: content_harvester
    # default entrypoint is python -m content_harvester.by_collection
    # override with tail -f /dev/null to keep container running for development
    entrypoint: tail -f /dev/null
    # optionally, remove entrypoint override and uncomment command definition
    # below to run a specific collection by id - 3433 in this example
    # command: ["3433"]
    working_dir: /
    volumes: 
      - ../rikolti_data:/rikolti_data
      - ../rikolti_content:/rikolti_content
      - ./:/content_harvester
    environment:
      - CONTENT_DATA_SRC=file:///rikolti_data
      - CONTENT_DATA_DEST=file:///rikolti_data
      - CONTENT_DEST=file:///rikolti_content
      - NUXEO=${NUXEO}
