AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  metadata-mapper-test

  SAM Template for Rikolti metadata-mapper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MetadataMapperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: metadata_mapper/
      Handler: lambda_shepherd.lambda_shepherd
      Runtime: python3.9
      Architectures:
        - x86_64
      #Events:
      #  MetadataMapper:
      #    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #    Properties:
      #      Path: /map
      #      Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #MetadataMapperApi:
  #  Description: "API Gateway endpoint URL for Prod stage for Metadata Mapper function"
  #  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MetadataMapperFunction:
    Description: "Metadata Mapper Lambda Function ARN"
    Value: !GetAtt MetadataMapperFunction.Arn
  MetadataMapperFunctionIamRole:
    Description: "Implicit IAM Role created for Metadata Mapper function"
    Value: !GetAtt MetadataMapperFunctionRole.Arn
